### ISSUE TITLE
Picke data truncated when running check_brewster.py

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [substellar/brewster#40]
I’m getting this issue with both python 3.7 and 3.11 when installing brewster

```
(brewster) [dbardalezgagliuffi@hpc-login2 brewster]$ python check_brewster.py
Traceback (most recent call last):
 File "check_brewster.py", line 6, in <module>
  results = [ct.NoCloud_Tdwarf(xpath,xlist),ct.MieClouds_Ldwarf(xpath,xlist)]
 File "/home/dbardalezgagliuffi/retrievals/brewster/code_test.py", line 141, in NoCloud_Tdwarf
  inlinetemps,inwavenum,linelist,gasnum,nwave = testkit.get_opacities(gaslist,w1,w2,press,xpath,xlist,malk)
 File "/home/dbardalezgagliuffi/retrievals/brewster/testkit.py", line 1308, in get_opacities
  rawwavenum, inpress, inlinetemps, inlinelist = pickle.load(open(lists[0], "rb"))
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by benburningham** [comment]
This is an issue with the target files being corrupted, rather than an bug in brewster.  

closing this issue.
